#!/usr/bin/env bash

set -xeuo pipefail
IFS=$'\n\t'

file=~/Private/passwords/aws

printHelp () {
cat <<EOF
$0 <1-4> [-p password] [-f file] [user] [-n]
$0 <ip>  ---||---

If password is given (before or after user), store it in file. Use -n to force-update the password of the CC.

Defaults:
- file  = $file
- user  = admin
- which = 1
EOF
}

password=
forceNoPassword=false
user=
which=
new=false # true if we want to force updating the CC's password from the VMS.

while [[ "$#" -gt 0 ]]; do
	case "$1" in
		-p)
			password="$2"
			if [[ -z "$password" ]]; then
				forceNoPassword=true
			fi
			shift
			;;
		-f)
			file="$2"
			shift
			;;
		-n)
			new=true
			;;
		-h|--help)
			printHelp
			exit 0
			;;
		*)
			if [[ -z "$which" ]]; then
				which="$1"
			elif [[ -z "$user" ]]; then
				user="$1"
			else
				printHelp
				exit 1
			fi
			;;
	esac
	shift
done

if [[ -z "$which" ]]; then
	which=AWS1
fi
if [[ -z "$user" ]]; then
	user=admin
fi

if [[ ! -z $password ]]; then
	get_cc_spec.sh -c $which -p $password
fi

# Check if we're getting a new password
if [[ $new = true ]]; then
	new='--no-cache'
else
	new=
fi

which=$(get_cc_spec.sh --get-ip -c $which)
usePassword=$(get_cc_spec.sh -c $which $new)
echo "Using IP $which and password '$usePassword'"

if [[ ! -z "$usePassword" ]] && [[ $forceNoPassword = false ]]; then
	sshpass -p $usePassword ssh "$user@$which"
else
	ssh "$user@$which"
fi

