#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'

if [[ $1 = -h ]]; then
	echo -e "${RED}logs <file> ([c] [in] <file>)${NC}"
	echo Give list of strings to exclude/include from the file.
	echo
	echo "c  -> toggle inclusion of colour. Default is to give coloured output. Using c once will disable it on strings going forward. Using c again will enable it for the following strings, and so on."
	echo "in -> include following file. Default is exclude."
	exit 0
fi

firstQuery=
query=""
in=
declare -a inArray
colour=true
file=$1
shift 1 # Exclusions from now on

while : ; do
	line="$1"
	if [[ "$line" = "" ]]; then
		break
	elif [[ "$line" = "c" ]]; then
		if [[ "$colour" = true ]]; then
			colour=false
		else
			colour=true
		fi
	elif [[ "$line" != "in" ]]; then
		query+=" | grep -v \"$line\""
	else
		in+=" | grep \"$2\""
		inArray+=("$2")
		shift 1
	fi
	shift 1
done

command="cat $file $query $in"
if [[ $colour = true ]]; then
	for value in "${inArray[@]}"; do
		command+=" | grep --color=always \"$value\""
	done
fi

echo -e "${RED}$command | tail -n 100${NC}"
(eval "$command") | tail -n 100