#!/bin/bash
function screenshot {
	for file in ./*png ; do
		eog "$file"
		read name;
		if [ "$name" = "delete" ]; then
			rm "$file"
		else
			mv "$file" "$name.png"
		fi
	done
	for file in ./*jpg; do
		eog "$file"
		read name;
		if [ "$name" = "delete" ]; then
			rm "$file"
		else
			mv "$file" "$name.jpg"
		fi
	done

	ls -1 *.png
	echo
	echo "Any png groups? (done stops)"

	read group
	while [ "$group" != "done" ]; do
		mkdir "$group"
		mv "$group"*.png "$group"
		mv "$group" ~/pictures/funny/
		read group
	done
	echo
	ls -1 *.jpg
	echo
	echo "Any jpg groups? (done stops)"
	read group
	while [ "$group" != "done" ]; do
		mkdir "$group"
		mv "$group"*.jpg "$group"
		mv "$group" ~/pictures/funny/
		read group
	done
	
	mv ~/*.png ~/*.jpg ~/pictures/funny/
}
