#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

debug=false
fullDebug=false
case "${1:-empty}" in
	empty)
	;;
	full)
		fullDebug=true
		debug=true
		;;
	*)
		debug=true
		;;
esac

cd ~/Downloads

# This effectively checks if the zip files exist. Requires pipefail.

logsFilePrefix="logs_cluster_"
if ! compgen -G "$logsFilePrefix"* > /dev/null; then
	if compgen -G "logs_node_"* > /dev/null; then
		echo "Cluster log doesn't exist. Use node logs."
		logsFilePrefix="logs_node_"
	elif compgen -G "logs_serverGroup_"* > /dev/null; then
		echo "Cluster log doesn't exist. Use server group logs."
		logsFilePrefix="logs_serverGroup_"
	elif compgen -G "log_bundle"* > /dev/null; then
		echo "Cluster log doesn't exist. Use log bundle logs."
		logsFilePrefix="log_bundle"
	elif compgen -G "logsBundle"* > /dev/null; then
		echo "Cluster log doesn't exist. Use logsBundle logs."
		logsFilePrefix="logsBundle"
	else
		echo "No known log name format"
		exit 1
	fi
	node=`ls -1 "$logsFilePrefix"* | head -n 1 | sed 's/'"$logsFilePrefix"'\(\([a-z]\|[0-9]\|\-\)*\).*/\1/'`
	node=/"$node"
fi

fullDate=`ls -1 "$logsFilePrefix"* | head -n 1 | sed 's/'"$logsFilePrefix"'[^.]*\([0-9]\{2\}.*\).zip/\1/'`
if compgen -G "ava_ui_logs*" > /dev/null; then
	deploymentName=`ls -1 ava_ui_logs* | head -n 1 | sed 's/ava_ui_logs_\(.*\)\./\1/'`
elif compgen -G "alta_aware_ui_logs*" > /dev/null; then
	deploymentName=`ls -1 alta_aware_ui_logs* | head -n 1 | sed 's/alta_aware_ui_logs_\([^.]*\).*/\1/'`
else
	echocolour "Unknown VMS. Give me a name (empty = <unknown>):"
	read name
	if [[ "$name" != "" ]]; then
		deploymentName=$name
	else
		deploymentName="<unknown>"
	fi
fi

year=`echo $fullDate | cut -d. -f 1`
month=`echo $fullDate | cut -d. -f 2`
day=`echo $fullDate | cut -d. -f 3`
hour=`echo $fullDate | cut -d. -f 4`
minute=`echo $fullDate | cut -d. -f 5`

logsName="$deploymentName"_"$day.$month.$year"

if [[ $debug = true ]]; then
cat <<EOF
Unpacking logs.
logs file prefix:       $logsFilePrefix
deployment name:        $deploymentName${node:-}
logs name:              $logsName
year:                   $year
month:                  $month
day:                    $day
hour:                   $hour
minute:                 $minute
EOF
echo
if [[ "$fullDebug" = true ]]; then
	exit 0
fi
fi

# Handle log backups
if [[ -d "./logs_$logsName" ]]; then
	[[ $debug = true ]] && echocolour "This log already exists. Moving it to backup."
	logsNum=`ls -1d */ | grep -c "^$logsName"__"backup" || true`
	# The `|| true` is here so grep doesn't return 1 when no match is found (which would terminate the script) 
	mv "logs_$logsName" "$logsName"__"backup_$logsNum" # Starts at 0, so will always work
fi

[[ $debug = true ]] && echocolour "Unzipping logs"
unzip "$logsFilePrefix"*.zip -d "logs_$logsName" 2>/dev/null

# Unzip nodes
if [[ -d "logs_$logsName/nodes" ]]; then
	[[ $debug = true ]] && echocolour "unzipping nodes"
	cd "logs_$logsName"/nodes

	for f in *.zip; do
		where=$(echo "$f" | sed 's/.zip//')
		unzip "$f" -d $where || true #1>/dev/null || true
		rm "$f"
	done
else
	[[ $debug = true ]] && echocolour "Skipping nodes -> no nodes in log bundle"
fi

# Store download information
cd ~/Downloads
echocolour "Writing download info"
cat > logs_$logsName/download_info <<EOF
This log is from deployment:
$deploymentName${node:-}

It was downloaded at:
$hour:$minute $day.$month. 20$year

Log file unpacked at:
$(date)
EOF

[[ $debug = true ]] && echocolour "Unpacking UI logs"
if compgen -G ava*.zip > /dev/null ; then unzip ava*.zip -d logs_$logsName/ui; fi
if compgen -G alta*.zip > /dev/null; then unzip alta*.zip -d logs_$logsName/ui; fi

cd ~/Downloads

# Analysis
cd logs_$logsName/nodes
echocolour "Analysing $(ls -1 | wc -l) servers"

for CC in ./*; do
	[[ $debug = true ]] && echocolour "Analysing $CC"
	cd $CC

	analysis=analysis
	touch $analysis

	for file in mgmt router access authenticator norm streamer ui; do
		echo "${file^^}" >> $analysis
		analyse_logs.sh -f $file.txt -w full >> $analysis
		echo >> $analysis
	done

	echo "PLATFORM" >> $analysis
	if [[ -f platform.txt ]]; then
		analyse_logs.sh -f platform.txt -w full >> $analysis
		echo >> $analysis
	elif [[ -f platform.log ]]; then
		analyse_logs.sh -f platform.log -w full >> $analysis
		echo >> $analysis
	else
		echo "WARNING - NO PLATFORM FILE"
	fi

	if [[ -f ana.txt ]]; then
		analyse_logs.sh -f ana.txt -w full >> $analysis
	fi

	if [[ -f store.txt ]]; then
		analyse_logs.sh -f store.txt -w full >> $analysis
	fi

	cd ..
done

[[ $debug = true ]] && echocolour "Deleting zips"
# Remove zips
cd ~/Downloads
rm log_bundle.zip logs_*.zip ava*.zip alta*.zip 2>/dev/null