#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'


printHelp () {
cat <<EOF
$0 <ip> -p <password> [user]

If password is given (before or after user), store it in the password file. Use -n to force-update the password of the CC.

Defaults:
- user  = admin
EOF
}

password=
user=
nodeIp=

while [[ "$#" -gt 0 ]]; do
	case "$1" in
		-p)
			password="${2:-}"
			shift
			;;
		-h|--help)
			printHelp
			exit 0
			;;
		*)
			if [[ -z "$nodeIp" ]]; then
				nodeIp="$1"
			elif [[ -z "$user" ]]; then
				user="$1"
			else
				printHelp
				exit 1
			fi
			;;
	esac
	shift
done

if [[ -z "$user" ]]; then
	user=admin
fi

if [[ ! -z "$password" ]]; then
	set -x
	sshpass -p $password ssh "$user@$nodeIp"
else
	set -x
	ssh "$user@$nodeIp"
fi
